# Generated by Django 5.1 on 2024-09-02 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('dynamicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pilotlog.dynamicmodel')),
            ],
            options={
                'db_table': 'aircraft',
            },
            bases=('pilotlog.dynamicmodel',),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('dynamicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pilotlog.dynamicmodel')),
            ],
            options={
                'db_table': 'flight',
            },
            bases=('pilotlog.dynamicmodel',),
        ),
    ]
