# Generated by Django 5.1 on 2024-09-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagePic',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimitRules',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyQuery',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyQueryBuild',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
                ('guid', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('_modified', models.BigIntegerField()),
                ('meta', models.JSONField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='pilotlog.aircraft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
